### ISSUE TITLE
Delete screens

### ISSUE THREAD

**Issue by scojocaru** [desbigi/DRS#23]
When deleting a task/case anything else, there's a confirmation screen with all entity details and a delete button, I would suggest to have a client side confirmation popup and after that delete the record, what do you think?

**Comment by BernieCrilly** [comment]
Do you mean instead of the confirmation screen that you would just have a popup message in the Edit Task / Edit Case screen and then delete - yes, I think that would be better

BUT
I am not 100% sure about cases or tasks being deleted at all, and not just closed as necesasry.  I will check with client and come back to you - so for now, maybe leave it in case we remove the delete functionality altogether

**Comment by BernieCrilly** [comment]
no cases / tasks can be deleted - leave like this unless requested otherwise by client
