### ISSUE TITLE
Duplicate cases appearing on Referral system

### ISSUE THREAD

**Issue by BernieCrilly** [desbigi/DRS#69]
Case created for Brid Casey appears twice on referral system.  This person appears on DSI instance as both a Donor (C0647) and Member (C0040)but in DRS the Case appears twice on the Member record (C0040)..

Separately, the dual records  may also cause confusion for DRS users - if they do a search of Service Users - and both Donor and member are in the list - how do we ensure the correct person is selected?  Who is the correct persons? we assume the member record should  take precedence over the Donor record.
 What is the best way to do this - show the coloured dots along with the name / address when they do a search in DRS? Will the remember what each colour is? or do we need to actually spell out - Donor / member?

**Comment by scojocaru** [comment]
The duplicate appeared because of the fast double-click on the create case button, I was able to reproduce it on DRS-DEV, so this is what most probably happened, I will put something in place to prevent this. Also, this has nothing to do with Brid Casey being twice in the system (as Donor and Member), just a coincidence.

Regarding the second issue, if both types (Donor & Member) are valid selections as service users in DRS,
we append the type at the end: 
....
Brid Casey (Donor)
Brid Casy (Member)
...
in case the search result returns two records with the same first and last names. Or any other way, to distinguish them, don't like colors.

**Comment by BernieCrilly** [comment]
Great thanks...good idea re donor/ member

**Comment by BernieCrilly** [comment]
I saw your comment re 3 Brid Caseys - team member can see that 2 are same person as address is the same, other one lives in different part of country... so yes, adding Donor or Member (or Non-member) will help them decide the one they want to select.

**Comment by scojocaru** [comment]
Fixed, available after next deployment
